### ISSUE TITLE
Duplication of blank nodes triples in the downloaded TTL file.

### ISSUE THREAD

**Issue by alvarocarrera** [gsi-upm/amor-segb#1]
If any blank node is logged to SEBB more than once, the downloaded graph contains those blank nodes repeated.

This is because rdflib assigns different ids every time the blank node is readed. Let's try with rdflib.ConjuntiveGraph class.

**Comment by alvarocarrera** [comment]
ConjuctiveGraph class is deprecated (replaced with Dataset class) and it does not solve our problem. Reading rdflib documentation in deep, we conclude that it is heavily recommended to avoid the usage of blank nodes when you are merging graphs from different sources (https://www.w3.org/TR/rdf11-mt/#shared-blank-nodes-unions-and-merges).

So, we **strongly recommend to avoid blank nodes** in any TTL triples that are logged to the Semantic Ethical Black Box. They will not _break_ the SEBB, but it can generate duplicated blank nodes (in the global graph) if they are sent several times to the SEBB.

**Comment by balkian** [comment]
This is by design. There is no way to tell two blank nodes apart. The only workaround is to give those nodes an ID.

Depending on your use case, you might get away with not storing these ids by generating them deterministically. e.g., with a hash of the triple.
